# https://golangci-lint.run/usage/configuration/
run:
  timeout: 2m

output:
  formats:
    - format: tab

issues:
  max-issues-per-linter: 0
  max-same-issues: 0

linters:
  enable:
    - dupl
    - depguard
    - gocritic
    - gocyclo
    - gofmt
    - govet
    - staticcheck
    - misspell
    - unconvert

linters-settings:
  depguard:
    rules:
      prevent_unmaintained_packages:
        list-mode: lax # allow unless explicitely denied
        files:
          - $all
          - "!$test"
        allow:
          - "github.com/clok"
          - "github.com/aws/aws-sdk-go"
